apiVersion: v1
data:
  proxy-connect-timeout: "60"
  proxy-read-timeout: "600"
  proxy-send-imeout: "600"
  hsts-include-subdomains: "false"
  client-max-body-size: "64m"
  proxy-body-size: "64m"
  server-name-hash-bucket-size: "256"
  X-Request-Start: t=${msec}
  hsts: "false"
  ssl-redirect: "false"
kind: ConfigMap
metadata:
  namespace: nginx-ingress
  name: nginx