apiVersion: v1
kind: Service
metadata:
  name: citibike
  namespace: prod

spec:
  ports:
  - port: 80
    targetPort: main-port
    protocol: TCP
  selector:
    app: citibike
    env:  prod
#  type: LoadBalancer